
[timeseries]
path = "examples/single_timeseries.csv"
date_format = "%Y-%m-%d"        # datetime format code.
first_day_of_water_year = 75    # 15 March

[components.first_migration]
timing = [292, 350]         # 1 Jan - 28 Feb (306 = 365 - (31 + 28))
magnitude = [10.0, 100.0]   # maybe use ma period of 3 or 5? If this gets longer duration should too.
duration = [">", 10]        # try values between 10 and 60.
